In [11]:
import json
from pathlib import Path

from PIL import Image
import pandas as pd

from data_augmentation import *

In [2]:
all_image_dir = "STARE/all/stare-images"
all_label_dir = "STARE/all/labels-ah"

all_image_files = sorted(list(Path(all_image_dir).glob("*.*")))
all_label_files = sorted(list(Path(all_label_dir).glob("*.*")))

len(all_image_files), len(all_label_files)

(20, 20)

In [3]:
split_fold4_file = "STARE/all/splits/STARE_2.json"

with open(split_fold4_file, "r") as f:
    splits = json.load(f)

splits

{'train': ['im0324.ppm',
  'im0239.ppm',
  'im0240.ppm',
  'im0004.ppm',
  'im0002.ppm',
  'im0162.ppm',
  'im0291.ppm',
  'im0082.ppm',
  'im0319.ppm',
  'im0001.ppm',
  'im0163.ppm',
  'im0044.ppm'],
 'validation': ['im0005.ppm', 'im0003.ppm', 'im0235.ppm', 'im0139.ppm'],
 'test': ['im0077.ppm', 'im0081.ppm', 'im0236.ppm', 'im0255.ppm']}

In [4]:
# test_image_stems = [
#     name.split(".")[0]
#     for name in splits["test"]
# ]
test_image_stems = [file.stem for file in all_image_files[-4:]]

test_label_stems = [stem + ".ah" for stem in test_image_stems]
test_image_stems, test_label_stems

(['im0255', 'im0291', 'im0319', 'im0324'],
 ['im0255.ah', 'im0291.ah', 'im0319.ah', 'im0324.ah'])

In [5]:
test_image_files = [file for file in all_image_files if file.stem in test_image_stems]
test_label_files = [file for file in all_label_files if file.stem in test_label_stems]

train_image_files = [file for file in all_image_files if file.stem not in test_image_stems]
train_label_files = [file for file in all_label_files if file.stem not in test_label_stems]

len(train_image_files), len(train_label_files), len(test_image_files), len(test_label_files)

(16, 16, 4, 4)

In [6]:
train_image_dir = "STARE/train/images"
os.makedirs(train_image_dir, exist_ok=True)

for file in train_image_files:
    image = Image.open(file)

    filename = Path(file).stem + ".png"
    image.save(Path(train_image_dir) / filename)

train_label_dir = "STARE/train/labels"
os.makedirs(train_label_dir, exist_ok=True)

for file in train_label_files:
    label = Image.open(file)

    filename = Path(file).stem + ".png"
    label.save(Path(train_label_dir) / filename)

In [7]:
# test_image_dir = "STARE/test/images"
# os.makedirs(test_image_dir, exist_ok=True)

# for file in test_image_files:
#     image = Image.open(file)

#     filename = Path(file).stem + ".png"
#     image.save(Path(test_image_dir) / filename)

# test_label_dir = "STARE/test/labels"
# os.makedirs(test_label_dir, exist_ok=True)

# for file in test_label_files:
#     label = Image.open(file)

#     filename = Path(file).stem + ".png"
#     label.save(Path(test_label_dir) / filename)

In [8]:
threadOPS(
    train_image_dir,
    train_image_dir,
    train_label_dir,       
    train_label_dir,       
)

In [9]:
train_image_files = list(Path(train_image_dir).glob("*.*"))
train_label_files = list(Path(train_label_dir).glob("*.*"))

len(train_image_files), len(train_label_files)

(208, 208)

In [12]:
train_image_df = pd.DataFrame({
    "path": map(str, train_image_files),
})
train_image_df["resolution_wh"] = train_image_df["path"].apply(lambda x: Image.open(x).size)
train_image_df.info()
train_image_df.head()

<class 'pandas.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   path           208 non-null    str
 1   resolution_wh  208 non-null    object
dtypes: object(1), str(1)
memory usage: 3.4+ KB

                                         path resolution_wh
0  STARE\train\images\diagonalFlip0im0001.png    (700, 605)
1  STARE\train\images\diagonalFlip0im0002.png    (700, 605)
2  STARE\train\images\diagonalFlip0im0003.png    (700, 605)
3  STARE\train\images\diagonalFlip0im0004.png    (700, 605)
4  STARE\train\images\diagonalFlip0im0005.png    (700, 605)

In [13]:
train_label_df = pd.DataFrame({
    "path": map(str, train_label_files),
})
train_label_df["resolution_wh"] = train_label_df["path"].apply(lambda x: Image.open(x).size)
train_label_df.info()
train_label_df.head()

<class 'pandas.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   path           208 non-null    str
 1   resolution_wh  208 non-null    object
dtypes: object(1), str(1)
memory usage: 3.4+ KB

                                            path resolution_wh
0  STARE\train\labels\diagonalFlip0im0001.ah.png    (700, 605)
1  STARE\train\labels\diagonalFlip0im0002.ah.png    (700, 605)
2  STARE\train\labels\diagonalFlip0im0003.ah.png    (700, 605)
3  STARE\train\labels\diagonalFlip0im0004.ah.png    (700, 605)
4  STARE\train\labels\diagonalFlip0im0005.ah.png    (700, 605)